### ISSUE TITLE
cuda version and triton behave differently

### ISSUE THREAD

**Issue by luxtiasco** [qwopqwop200/GPTQ-for-LLaMa#128]
cuda version and triton behave differently when --act-order --true-sequential --groupsize 128 is applied at the same time

In this case, the triton branch is all right, but the cuda version will have strange output, such as irrelevant to the input, a large number of repetitions.

**Comment by dulanyw** [comment]
I haven't been able to use the triton branch, but observed the same in the CUDA branch on Windows.

**Comment by j4ded** [comment]
> In this case, the triton branch is all right, but the cuda version will have strange output, such as irrelevant to the input, a large number of repetitions.

i remember wasting a few hours quantizing a while ago using groupsize, before triton, and having nonsense repetition of words as output. it has been a while since i have looked over this repo, but that may be to blame if groupsize still doesn't work with cuda. if groupsize was implemented for cuda, then idk.

**Comment by Ph0rk0z** [comment]
I used groupsize with cuda because people encoded models that way. I think it just didn't support true sequential and act order + groupsize.

True sequential + act order without group size still gives passable scores and I'd rather have it reply under a minute to a chat message than wait for a few points of benchmark :D

**Comment by luxtiasco** [comment]
> I used groupsize with cuda because people encoded models that way. I think it just didn't support true sequential and act order + groupsize.
> 
> True sequential + act order without group size still gives passable scores and I'd rather have it reply under a minute to a chat message than wait for a few points of benchmark :D

but it matters with those languages that a word takes multiple tokens... Without that, it frequently gives out broken words.
I'd give up windows and use triton then.

**Comment by Ph0rk0z** [comment]
Heh.. I don't use windows but I have a compute 6.1 card.

**Comment by qwopqwop200** [comment]
There is no difference computationally between cuda and tritons.
