### ISSUE TITLE
why disable tf32 ?

### ISSUE THREAD

**Issue by tpoisonooo** [qwopqwop200/GPTQ-for-LLaMa#192]
I noticed that  you explicitly disable `tf32`  [here](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/fcf403ffff35b1d28fdb00d0d01f4dbd3fc11c31/gptq.py#L100)

[CUDA semantics](https://pytorch.org/docs/stable/notes/cuda.html#tf32-on-ampere) says `tf32` would be  10x faster for matmul,  why disable it ?

**Comment by qwopqwop200** [comment]
I do not know. It would be good to ask the GPTQ author.

**Comment by aljungberg** [comment]
TF32 has lower accuracy which is why it's now [disabled by default](https://github.com/pytorch/pytorch/pull/76509) in Pytorch. Sounds like a reasonable thing to disable during quantisation since you want to produce the highest quality output model possible.

Curious if it could be enabled during eval (inference) though. Since these statements run at the import level, they'll kick in in both cases.

**Comment by aljungberg** [comment]
Just tested this with 13B model, 1884 context tokens, generating 115 tokens. Seems to make no difference at inference time. I guess we don't have a lot of `float32` stuff going on, everything is `float16` once unpacked, except a couple of accumulators which can't benefit since they're not matmul'ed.

**Comment by Dessix** [comment]
Running on the recent `fastest-inference-speed` branch, I got a nearly 2x speedup from:
```
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
torch.backends.cuda.enable_mem_efficient_sdp(True)
torch.backends.cuda.enable_math_sdp(True)
torch.backends.cuda.enable_flash_sdp(True)
```
But appear to have received mildly reduced model coherence from anecdotal experience. I'd like to see this measured in actual benchmarks, but I lack the experience to do so myself. It seems it's still an area worth investigating, considering it took me over 200 tokens per second on Vicuna13B.

Edit:
My apologies- this occurs with only the SDP enablement as well. The tf32 cores appear to reduce heat output but not visibly improve rate of token production.
