### ISSUE TITLE
Will loras work with this?

### ISSUE THREAD

**Issue by fblissjr** [qwopqwop200/GPTQ-for-LLaMa#50]
See: https://github.com/tloen/alpaca-lora/blob/main/generate.py

Tried modifying the code to look like this, but no luck initially.

from peft import PeftModel
from transformers import LLaMATokenizer, LLaMAForCausalLM, GenerationConfig

tokenizer = LLaMATokenizer.from_pretrained("decapoda-research/llama-7b-hf")

model = LLaMAForCausalLM.from_pretrained(
    "decapoda-research/llama-7b-hf",
    load_in_8bit=True,
    device_map="auto",
)
model = PeftModel.from_pretrained(model, "tloen/alpaca-lora-7b")

**Comment by qwopqwop200** [comment]
Maybe now I can make it workable.

**Comment by clxyder** [comment]
Did we ever get this working? I tried doing the same with https://huggingface.co/nomic-ai/gpt4all-lora, but I had no luck.

This is the notebook I am working on: https://colab.research.google.com/drive/1cUab6I8kf5FMvdCYJGRaqMqKvMpcVJ0F?usp=sharing

**Comment by clxyder** [comment]
Hey @qwopqwop200 were we able to make this work?

I get an error when attempting to quantize the above setup.

Something along the lines that `model.model` does not have the attribute `layers`

https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/5731aa11de56affe6e8c88cea66a171045ad1dce/llama.py#L29

Turns out the layers are in `model.model.model.layers`, but that would only get the base model layers and not the LoRA ones too, right?
