### ISSUE TITLE
llama_inference_offload.py hardcoded to cuda:0

### ISSUE THREAD

**Issue by generic-username0718** [qwopqwop200/GPTQ-for-LLaMa#93]
Pretty sure your llama_inference_offload script is hard coded for a single device

DEV = torch.device('cuda:0')

any way to adapt this to pass a device map for multi-gpu configurations?

**Comment by qwopqwop200** [comment]
Since this only considers a single GPU, we do not intend to change it, but we think it can be implemented through the following changes.
https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/triton/llama_inference_offload.py#L12
```
DEV = [torch.device('cuda:0') for i in range(pre_layer//2)] +  [torch.device('cuda:1') for i in range(pre_layer//2)] 
```
https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/triton/llama_inference_offload.py#L231
```
    for i in range(pre_layer):
        model.model.layers[i].to(DEV[i])
    model.model.embed_tokens.to(DEV[0])
    model.model.norm.to(DEV[0])
    model.lm_head.to(DEV[0])
    model.model.preload = pre_layer
    print('Done.')
    return model
```
