### ISSUE TITLE
Much slower speed with the latest updates

### ISSUE THREAD

**Issue by oobabooga** [qwopqwop200/GPTQ-for-LLaMa#96]
For the same prompts and with `do_sample=False` (deterministic sampling), these are the speeds that I get for `llama-7b` quantized with groupsize=128:

| Commit | Speed |
|-------------|----------|
|b8208054e990ddb51e26384c2a6d28e1c6d686c3 | Output generated in 2.71 seconds (36.48 tokens/s, 99 tokens, context 16) |
| 4e141a8c4725958b187f9d5d1ffac13f22a204c9 (latest) | Output generated in 34.52 seconds (2.87 tokens/s, 99 tokens, context 16)  |

**Comment by qwopqwop200** [comment]
First of all, I changed the main branch to cuda.
I think it's probably a bottleneck caused by the pytorch implementation.

**Comment by awatuna** [comment]
Same here, it dropped from 13 to 2 tokens/s.
I upgraded pytorch to 2.0.0 as per readme (was 1.13.1), still the same.

**Comment by qwopqwop200** [comment]
Please use [cuda baranch](https://github.com/qwopqwop200/GPTQ-for-LLaMa/tree/cuda) now.

**Comment by oobabooga** [comment]
Thank you, using the default branch (cuda) and compiling again with `python setup_cuda.py install` I got the old speed back (even better now):

Output generated in 2.03 seconds (48.85 tokens/s, 99 tokens, context 16)

**Comment by aljungberg** [comment]
I believe the "unpack once then matmul" optimisation in the `pytorch` branch only makes sense when you have a sufficiently large batch size or sequence to work on. If you're only doing each layer's forward pass on a single token, it's better to unpack during multiplication like the cuda kernels do. So you'll want the cuda branch.

You have to reach a certain threshold (and the original PR #87 suggested that was about 128 units of work) for it to be better to unpack into VRAM instead of doing a "streaming decompress" like the cuda kernels do.

If you're just making 1 token, which you will be once the context has been processed and you're generating step by step, then the "unpack first" strategy doesn't make sense because you'll unpack all the weights into temporary memory, then run a matmul against them and immediately throw the unpacked data away as you move to the next layer. So for the 30b model you're writing 60GB of floats to memory or so per token generated, and then reading it back in the matmul. Meanwhile if you stream from quant memory you're just reading ~30GB of data into L1 cache.

**Comment by tensiondriven** [comment]
This level of technical detail is supremely helpful to people like me (technical hobbyists) - My experience has been that finding succinct explanations for these things that are grounded in concrete use cases is exceptionally difficult.  Just wanted to say thank you for taking the time to write.

**Comment by Qubitium** [comment]
@aljungberg Sounds like the 7900x3d variants with 96MB more L3 cache may perform much better than 13900k in the "unpack once then matmul" pytroch implementation which requires massive ram <-> cpu read/write ops for the likes of 30B models.

**Comment by ndkling** [comment]
@diegomontoya I have a 7900 XTX and an RTX 3090 and I would love to test that excellent hypothesis, but [ROCm doesn't support the card yet](https://github.com/RadeonOpenCompute/ROCm/issues/1880).  I've been searching for any reason not to return it, and that would be enormously compelling.

**Comment by Qubitium** [comment]
@ndkling  We have a small misunderstanding there. I meant the AMD 7900X3D cpu, not the 7900XTX gpu.  =)

**Comment by ndkling** [comment]
@diegomontoya Ah, my mistake.  Thank you for correcting me.  I had read about the unique cache somewhere while researching and obviously internalized it wrong.

**Comment by alexconstant9108** [comment]
> I believe the "unpack once then matmul" optimisation...

@aljungberg could this optimization be *dynamically* turned on / off during runtime depending on batch or sequence size? That is the code to decide whether to use the "unpack once then matmul" optimisation or not.

**Comment by aljungberg** [comment]
> > I believe the "unpack once then matmul" optimisation...
> 
> @aljungberg could this optimization be _dynamically_ turned on / off during runtime depending on batch or sequence size? That is the code to decide whether to use the "unpack once then matmul" optimisation or not.

That's exactly how it works! Just not in the `pytorch` branch which was the default when this issue was opened. 

The cuda branch uses the original kernel for small batches but [switches to "unpack once"](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/a7143402398ba688fb2f8f6429ee1e6b476b6720/quant.py#L307) after a certain threshold. This works really well, at least in my testing, since there's a mix of more batch-y work and step by step work in the normal interactive text generation case. (First you process the context to fill the kv cache and generate the auto-regressive hidden state, then you go 1 by 1 for the generate/sample loop. So in that workload the optimisation kicks in for the first part since you've got up to 2048 tokens you can process in essentially one go. The optimisation makes the initial context preprocessing like 5x faster.

On the pytorch branch the unpack once model is used all the time, so it's not a good fit for the interactive use case. Any gains you make processing the context quickly you lose in the 1-by-1 stage as discussed above.


> @aljungberg Sounds like the 7900x3d variants with 96MB more L3 cache may perform much better than 13900k in the "unpack once then matmul" pytroch implementation which requires massive ram <-> cpu read/write ops for the likes of 30B models.

Well, if you're running inference on your CPU that's certainly going to be useful! An unpacked layer of the 7B model is like 100 MB if my back of the napkin math is right, so you could squeeze a significant part into your L3 cache. 

But normally you run on GPU and the unpacking happens entirely from and to GPU VRAM. The beefiest consumer GPU, an RTX 4090, has "only" 72 MB of L2 cache,  which doesn't hurt but there's no chance you'll hold both the unpacked data and the actual input and output tensors in L2 at once.

**Comment by ndkling** [comment]
@aljungberg This time I'm not confused: the AMD 7900 XTX GPU has 96 MB of L2 cache, more than the 4090.  Maybe not enough to matter, but I'm trying to save face here.

**Comment by qwopqwop200** [comment]
Maybe solved the problem.
